spring:
  session:
    store-type: redis
  # Redis-x64-3.2.100 \ redis-server.exe 실행
  redis:
    host: 127.0.0.1
    port: 6379
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: javaServiceTreeFramework-BackendCore-Swagger
          uri: http://127.0.0.1:31313
          predicates:
            - Path=/backend-core-api/**
        - id: javaServiceTreeFramework-EngineFire-Swagger
          uri: http://127.0.0.1:33333
          predicates:
            - Path=/engine-fire-api/**
        - id: javaServiceTreeFramework-BackendCore-AuthAnon
          uri: http://127.0.0.1:31313
          predicates:
            - Path=/auth-anon/**
          filters:
            - RewritePath=/auth-anon/api/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-BackendCore-AuthUser
          uri: http://127.0.0.1:31313
          predicates:
            - Path=/auth-user/**
          filters:
            - RewritePath=/auth-user/api/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-BackendCore-AdminUser
          uri: http://127.0.0.1:31313
          predicates:
            - Path=/auth-admin/**
          filters:
            - RewritePath=/auth-admin/api/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-BackendCore-DWR
          uri: http://127.0.0.1:31313
          predicates:
            - Path=/dwr/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-EngineFire-Search
          uri: http://127.0.0.1:33333
          predicates:
            - Path=/engine-search-api/**
          filters:
            - RewritePath=/engine-search-api/(?<path>.*), /$\{path}
  security:
    auth:
      success:
        redirect-url: /arms/template.html?page=pdService

    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://www.313.co.kr/auth/realms/master
            token-uri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username
        registration:
          middle-proxy:
            scope: openid
            realm: master
            server-url: http://www.313.co.kr/auth
            provider: keycloak
            client-id: Java-Service-Tree-Framework-Middle-Proxy
            client-secret: f1011641-e4d4-4dc8-b177-7834fcf7d041
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/middle-proxy"
  main:
    web-application-type: reactive

backendURL : http://127.0.0.1:31313

logging:
  level:
    org.springframework.cloud.gateway: debug

ribbon:
  eureka:
    enabled: false
