spring:
  application:
    name: javaServiceTreeFrameworkMiddleProxy
    zipkin:
      enabled: true
      service.name: zipkin-service
      sender.type: web
      base-url: http://313.co.kr:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  cloud:
    gateway:
      httpclient:
        connect-timeout: 7200000
        response-timeout: 7200000

server:
  port: 13131

io:
  netty:
    resolver:
      dns:
        native: false


serverUrl: http://www.313.co.kr/auth
realm: master
tokenUrl: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/token
clientId: Java-Service-Tree-Framework-Middle-Proxy
clientSecret: f1011641-e4d4-4dc8-b177-7834fcf7d041
