spring:
  application:
    name: javaServiceTreeFrameworkMiddleProxy
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  cloud:
    gateway:
      httpclient:
        connect-timeout: 7200000
        response-timeout: 7200000
        pool:
          max-connections: 500
          max-idle-time: 20000 #20 sec
          max-life-time: 60000 #60 sec
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost","http://127.0.0.1","http://localhost:9999","http://127.0.0.1:9999","http://313.co.kr","http://www.313.co.kr","http://313.co.kr:9999","http://www.313.co.kr:9999","http://a-rms.net","http://www.a-rms.net","http://www.a-rms.net:9999","http://a-rms.net:9999","http://arms.mmc-mad.com"
            allow-credentials: true # JWT 나 쿠키를 사용해 메시지를 보내야 할 경우 true
            allowedHeaders: '*'
            allowedMethods: # 메서드를 명시하지 않으면 안되는 경우도 있기 때문에 메서드는 명시해주는 편이 좋다고 한다.
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

server:
  port: 13131

io:
  netty:
    resolver:
      dns:
        native: false

springfox:
  documentation:
    swagger:
      v2:
        path: /middle-proxy-api
    swagger-ui:
      base-url: /middle-proxy-api