spring:
  profiles:
    active: live
  session:
    store-type: redis
  redis:
    host: 192.168.25.46
    port: 6379

backendURL : http://192.168.25.46:31313

zuul:
  ignoredServices: "*"
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    javaServiceTreeFrameworkBackendServer-DWR:
      path: /dwr/**
      url: http://192.168.25.46:31313/dwr
      sensitiveHeaders: Cookie,Set-Cookie
    javaServiceTreeFrameworkBackendServer-AuthAnon:
      path: /auth-anon/api/**
      url: http://192.168.25.46:31313
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true
    javaServiceTreeFrameworkBackendServer-AuthUser:
      path: /auth-user/api/**
      url: http://192.168.25.46:31313
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true
    javaServiceTreeFrameworkBackendServer-AuthAdmin:
      path: /auth-admin/api/**
      url: http://192.168.25.46:31313
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true

ribbon:
  eureka:
    enabled: false