spring:
  application:
    name: javaServiceTreeFrameworkMiddleProxy
  #  zipkin:
  #    enabled: true
  #    service.name: zipkin-service
  #    sender.type: web
  #    base-url: http://192.168.25.31:9411
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB


server:
  port: 13131

io:
  netty:
    resolver:
      dns:
        native: false


serverUrl: http://www.313.co.kr/auth
realm: master
tokenUrl: http://www.313.co.kr/auth/realms/master/protocol/openid-connect/token
clientId: Java-Service-Tree-Framework-Middle-Proxy
clientSecret: f1011641-e4d4-4dc8-b177-7834fcf7d041
