spring:
  profiles:
    active: dev
  session:
    store-type: redis
  redis:
    host: 192.168.25.46
    port: 6379

backendURL : http://127.0.0.1:31313

zuul:
  igoredServices: '*'
  host:
    conect-timeout-millis: 600000
    socket-timeout-millis: 600000
  routes:
    javaServiceTreeFrameworkBackendServer-DWR:
      path: /dwr/**
      url: http://127.0.0.1:31313/dwr
      sensitiveHeaders: Cookie,Set-Cookie
    javaServiceTreeFrameworkBackendServer-AuthAnon:
      path: /auth-anon/api/**
      url: http://127.0.0.1:31313
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true
    javaServiceTreeFrameworkBackendServer-AuthUser:
      path: /auth-user/api/**
      url: http://127.0.0.1:31313
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true
    javaServiceTreeFrameworkBackendServer-AuthAdmin:
      path: /auth-admin/api/**
      url: http://127.0.0.1:31313
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: true

ribbon:
  eureka:
    enabled: false