spring:
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    service.name: zipkin-service
    sender.type: web
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: javaServiceTreeFramework-BackendCore-Swagger
          uri: http://backend-core:31313
          predicates:
            - Path=/backend-core-api/**
        - id: javaServiceTreeFramework-EngineFire-Swagger
          uri: http://engine-fire:33333
          predicates:
            - Path=/engine-fire-api/**
        - id: javaServiceTreeFramework-BackendCore-AuthAnon
          uri: http://backend-core:31313
          predicates:
            - Path=/auth-anon/**
          filters:
            - RewritePath=/auth-anon/api/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-BackendCore-AuthUser
          uri: http://backend-core:31313
          predicates:
            - Path=/auth-user/**
          filters:
            - RewritePath=/auth-user/api/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-BackendCore-AdminUser
          uri: http://backend-core:31313
          predicates:
            - Path=/auth-admin/**
          filters:
            - RewritePath=/auth-admin/api/(?<path>.*), /$\{path}
        - id: javaServiceTreeFramework-BackendCore-DWR
          uri: http://backend-core:31313/dwr
          predicates:
            - Path=/dwr/**
          filters:
            - RewritePath=/(?<path>.*), /$\{path}
  security:
    auth:
      success:
        redirect-url: /arms/template.html?page=pdService

    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://${ARMS_BASE_ADDR}/auth/realms/master
            token-uri: http://${ARMS_BASE_ADDR}/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://${ARMS_BASE_ADDR}/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: http://${ARMS_BASE_ADDR}/auth/realms/master/protocol/openid-connect/userinfo
            jwk-set-uri: http://${ARMS_BASE_ADDR}/auth/realms/master/protocol/openid-connect/certs
            user-name-attribute: preferred_username

        registration:
          middle-proxy:
            scope: openid
            realm: master
            server-url: http://${ARMS_BASE_ADDR}/auth
            provider: keycloak
            client-id: Java-Service-Tree-Framework-Middle-Proxy
            client-secret: f1011641-e4d4-4dc8-b177-7834fcf7d041
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/middle-proxy"
  main:
    web-application-type: reactive

backendURL : http://backend-core:31313

logging:
  level:
    proxy: info

ribbon:
  eureka:
    enabled: false
