spring:
  application:
    name: javaServiceTreeFrameworkMiddleProxy
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  cloud:
    gateway:
      httpclient:
        connect-timeout: 7200000
        response-timeout: 7200000
        pool:
          max-connections: 500
          max-idle-time: 20000 #20 sec
          max-life-time: 60000 #60 sec
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            allow-credentials: true

server:
  port: 13131

io:
  netty:
    resolver:
      dns:
        native: false

springfox:
  documentation:
    swagger:
      v2:
        path: /middle-proxy-api
    swagger-ui:
      base-url: /middle-proxy-api